data/urls.py
from django.urls import path

from data import views

app_name = 'data'

urlpatterns = [
    path('', views.redirect_home, name='main_view'),
    path('collection/', views.collection_home, name='collection_home'),
    path(
        'disbursement/e-wallets/',
        views.DisbursementHomeView.as_view(),
        name='e_wallets_home',
    ),
    path(
        'disbursement/bank-wallets/',
        views.BanksHomeView.as_view(),
        name='bank_wallets_home',
    ),
    path(
        'disbursement/bank-cards/',
        views.BanksHomeView.as_view(),
        name='bank_cards_home',
    ),
    path('delete/(<pk>/', views.FileDeleteView.as_view(), name='file_delete'),
    path('documents/<doc_id>/', views.document_view, name='doc_viewer'),
    path('download_doc/<doc_id>/', views.doc_download, name='download_doc'),
    path('format/list', views.FormatListView.as_view(), name='list_format'),
    path(
        'document/collection/<pk>/',
        views.RetrieveCollectionData.as_view(),
        name='doc_collection_detail',
    ),
    path(
        'transaction/report-problem/<trx_type>/<trx_id>/',
        views.ReportProblemView.as_view(),
        name='report_problem',
    ),
]

disbursement/urls.py
from django.urls import path

from .views import (
    AgentsListView, BalanceInquiry,
    SuperAdminAgentsSetup, disburse, DisbursementDocTransactionsView,
    download_failed_validation_file, ExportClientsTransactionsReportPerSuperAdmin,
    failed_disbursed_for_download, SingleStepTransactionsView,
    DownloadSampleSheetView, download_exported_transactions, HomeView,
    DisbursementDataListView, OrangeBankWalletListView, BanksListView,CreatePaymentLink, DisbursePaymentLink
)


app_name = 'disbursement'

client_urls = [
    path('agents/', AgentsListView.as_view(), name='agents_list'),
    path('home/', HomeView.as_view(), name='home_root'),
    path('home/portal-transactions/', DisbursementDataListView.as_view(), name='vf_et_aman_list'),
    path('home/portal-transactions-orange/', OrangeBankWalletListView.as_view(), name='orange_bank_wallet_list'),
    path('home/portal-transactions-banks/', BanksListView.as_view(), name='banks_list'),
    path('budget/inquiry/<str:username>/', BalanceInquiry.as_view(), name='balance_inquiry'),
    path('client/creation/agents/<token>/', SuperAdminAgentsSetup.as_view(), name='add_agents'),
]

urlpatterns = [
    path('disburse/single-step/', SingleStepTransactionsView.as_view(), name='single_step_list_create'),
    path('disburse_call/<doc_id>/', disburse, name='disburse'),
    path('disburse/export-sample-file/', DownloadSampleSheetView.as_view(), name='export_sample_file'),
    path('disburse/report/<doc_id>/', DisbursementDocTransactionsView.as_view(), name='disbursed_data'),
    path('disburse/export_failed_download/<doc_id>/', failed_disbursed_for_download, name='download_failed'),
    path('disburse/download_exported_transactions/', download_exported_transactions, name='download_exported'),
    path(
            'disburse/export-clients-transactions-report/',
            ExportClientsTransactionsReportPerSuperAdmin.as_view(),
            name='export_clients_transactions_report'
    ),
    path('disburse/export_failed_validation_download/<doc_id>/',
         download_failed_validation_file, name='download_validation_failed'),
    path('create/payment-link/', CreatePaymentLink.as_view(), name='create_payment_link'),
    path('disburse/payment/link/<payment_token>/', DisbursePaymentLink.as_view(), name='disburse_payment_link')
]

urlpatterns += client_urls

docs/urls.py
from django.urls import re_path, path
from django.views.generic import TemplateView

from .views import serve_docs


app_name = 'docs'


urlpatterns = [
    path('docs/swagger-ui/', TemplateView.as_view(
            template_name='instant_cashin/swagger_api_docs.html',
            extra_context={'schema_url': 'openapi-schema'}
        ), name='swagger-ui'),
    re_path(r'^docs/(?P<path>.*)$', serve_docs, name='instant_docs'),
]

instant_cashin/api/urls.py
from django.urls import path

from .base_views import (  # TopupbalanceAPIView,
    AmanTransactionCallbackHandlerAPIView, BudgetInquiryAPIView,
    BulkTransactionInquiryAPIView, Calculate_fees_and_vat_APIView,
    CancelAmanTransactionAPIView, HoldBalanceAPIView,
    InstantDisbursementAPIView, ReleaseBalanceAPIView, ReturnBalanceAPIView,
    SingleStepDisbursementAPIView)

app_name = 'instant_api'

urlpatterns = [
    # User Inquiry Feature is DISABLED for now! and HIDDEN from the Docs.
    # path('inquire-user/', InstantUserInquiryAPIView.as_view(), name='inquire_user'),
    path('budget/inquire/', BudgetInquiryAPIView.as_view(), name='budget_inquiry'),
    path(
        'transaction/aman-callback/',
        AmanTransactionCallbackHandlerAPIView.as_view(),
        name='aman_trx_callback',
    ),
    path(
        'transaction/inquire/',
        BulkTransactionInquiryAPIView.as_view(),
        name='bulk_transaction_inquiry',
    ),
    path('disburse/', InstantDisbursementAPIView.as_view(), name='instant_disburse'),
    path('hold-balance/', HoldBalanceAPIView.as_view(), name='hold_balance'),
    path('release-balance/', ReleaseBalanceAPIView.as_view(), name='release_balance'),
    path('return-balance/', ReturnBalanceAPIView.as_view(), name='return_balance'),
    path(
        'disburse/single-step/',
        SingleStepDisbursementAPIView.as_view(),
        name='disburse_single_step',
    ),
    path(
        'transaction/aman/cancel/',
        CancelAmanTransactionAPIView.as_view(),
        name='cancel_aman_transaction',
    ),
    # path('topupbalance-request/',TopupbalanceAPIView.as_view(),name='topupbalance_request'),
    path(
        'calc-fees-vat/', Calculate_fees_and_vat_APIView.as_view(), name='calc_fees_vat'
    ),
]

instant_cashin/urls.py
from django.urls import path

from .views import BankTransactionsListView, InstantTransactionsListView


app_name = 'instant_cashin'

urlpatterns = [
    path('instant-transactions/wallets/', InstantTransactionsListView.as_view(), name='wallets_trx_list'),
    path('instant-transactions/banks/', InstantTransactionsListView.as_view(), name='banks_trx_list'),
]

users/urls.py
# -*- coding: utf-8 -*-

from django.contrib.auth import views as django_auth_views
from django.urls import path
from oauth2_provider import views as oauth2_views

from payouts.views import no_agent_error_view
from users.views.main_views import CallbackURLEdit

from . import views

app_name = 'users'


client_urls = [
    path('clients/', views.Clients.as_view(), name='clients'),
    path('client/creation/', views.SuperAdminRootSetup.as_view(), name='add_client'),
    path(
        'client/delete/<str:username>/',
        views.SuperAdminCancelsRootSetupView.as_view(),
        name='delete_client',
    ),
    # 'Adding agents' -url- to the clients is at the disb. app urlpatterns
    path(
        'client/fees-setup/<token>/', views.ClientFeesSetup.as_view(), name='add_fees'
    ),
    path(
        'fees-profile/',
        views.SuperAdminFeesProfileTemplateView.as_view(),
        name='super_fees_profile',
    ),
    path(
        'client/fees-setup/edit/<str:username>/',
        views.CustomClientFeesProfilesUpdateView.as_view(),
        name='update_fees',
    ),
    path(
        'client/fees-setup/update/<str:username>/',
        views.ClientFeesUpdate.as_view(),
        name='update_fees_profile',
    ),
    path('client/toggle/', views.toggle_client, name='toggle'),
]

super_and_root_urls = [
    path('members/', views.Members.as_view(), name='members'),
    path('user/delete/', views.UserDeleteView.as_view(), name='delete'),
    path('settings/branding/', views.EntityBranding.as_view(), name='entity_branding'),
]

support_urls = [
    path('support/home/', views.SupportHomeView.as_view(), name='support_home'),
    path(
        'support/documents/<username>/',
        views.DocumentsForSupportListView.as_view(),
        name='documents_list',
    ),
    path(
        'support/documents/<username>/<doc_id>/',
        views.DocumentForSupportDetailView.as_view(),
        name='doc_detail',
    ),
    path('support/', views.SupportUsersListView.as_view(), name='support'),
    path(
        'support/creation/',
        views.SuperAdminSupportSetupCreateView.as_view(),
        name='add_support',
    ),
    path(
        'support/clients/',
        views.ClientsForSupportListView.as_view(),
        name='support_clients_list',
    ),
    path(
        'support/clients/Credentials',
        views.OnboardingNewInstantAdmin.as_view(),
        name='support_clients_credentials',
    ),
    path(
        'support/clients/Credentials/<client_id>',
        views.ClientCredentialsDetails.as_view(),
        name='support_clients_credentials_details',
    ),
]

onboard_user_urls = [
    path(
        'onboard-user/home/',
        views.OnbooardUserHomeView.as_view(),
        name='onboard_user_home',
    ),
    path('onboard-user/', views.OnboardUsersListView.as_view(), name='onboard_user'),
    path(
        'onboard-user/creation/',
        views.SuperAdminOnboardSetupCreateView.as_view(),
        name='add_onboard_user',
    ),
]

supervisor_user_urls = [
    path(
        'supervisor/home/',
        views.SupervisorUserHomeView.as_view(),
        name='supervisor_home',
    ),
    path('supervisor/', views.SupervisorUsersListView.as_view(), name='supervisor'),
    path(
        'supervisor/creation/',
        views.SuperAdminSupervisorSetupCreateView.as_view(),
        name='add_supervisor_user',
    ),
    path(
        'supervisor/reactivate_support_user',
        views.SupervisorReactivateSupportView.as_view(),
        name='reactivate_support_user',
    ),
]

disbursement_setups_urls = [
    path(
        'setting-up/disbursement-pin',
        views.PinFormView.as_view(),
        name='setting-disbursement-pin',
    ),
    path(
        'setting-up/disbursement-makers',
        views.MakerFormView.as_view(),
        name='setting-disbursement-makers',
    ),
    path(
        'setting-up/disbursement-levels',
        views.LevelsFormView.as_view(),
        name='setting-disbursement-levels',
    ),
    path(
        'setting-up/disbursement-checkers',
        views.CheckerFormView.as_view(),
        name='setting-disbursement-checkers',
    ),
    path(
        'setting-up/disbursement-formats',
        views.CategoryFormView.as_view(),
        name='setting-disbursement-formats',
    ),
    path('members/maker/add/', views.AddMakerView.as_view(), name='add_maker'),
    path('members/checker/add/', views.AddCheckerView.as_view(), name='add_checker'),
    path('levels/', views.LevelsView.as_view(), name='levels'),
    path('change_pin/', views.change_pin_view, name='change_pin'),
    path(
        'vodafone/change-pin/',
        views.vodafone_change_pin_view.as_view(),
        name='vodafone_change_pin',
    ),
]

instant_urls = [
    path('members/viewer/add/', views.ViewerCreateView.as_view(), name='add_viewer'),
    path(
        'members/api-checker/add/',
        views.APICheckerCreateView.as_view(),
        name='add_api_checker',
    ),
]

password_handling_urls = [
    path('change_password/<user>/', views.change_password, name="change_password"),
    path(
        'forgot-password/', views.ForgotPasswordView.as_view(), name="forgot_password"
    ),
    path('password/reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path(
        'password/reset/done/',
        django_auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'password/reset/<uidb64>/<token>/',
        django_auth_views.PasswordResetConfirmView.as_view(
            success_url='/', template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'password/done/',
        django_auth_views.PasswordResetCompleteView.as_view(),
        {'extra_context': {'login_url': '/user/login'}},
        name='password_reset_complete',
    ),
]

oauth2_provider_urls = [
    path("api/secure/o/token/", oauth2_views.TokenView.as_view(), name="oauth2_token"),
    path(
        "oauth2/keys/<username>/",
        views.OAuth2ApplicationDetailView.as_view(),
        name="oauth2_detail",
    ),
]

sessions_urls = [
    path('sessions/', views.SessionListView.as_view(), name='session_list'),
    path(
        'sessions/other/delete/',
        views.SessionDeleteOtherView.as_view(),
        name='session_delete_other',
    ),
    path(
        'sessions/<str:pk>/delete/',
        views.SessionDeleteView.as_view(),
        name='session_delete',
    ),
]

system_urls = [
    path(
        'creation/admin/<token>/',
        views.OnboardingNewMerchant.as_view(),
        name='creation_admin',
    ),
]

urlpatterns = [
    path('user/login/', views.login_view, name='user_login_view'),
    path('user/logout/', views.ourlogout, name='logout'),    
    path('user/no-agent/', no_agent_error_view, name='no_agent_error'),
    path('account/token/', views.OTPLoginView.as_view(), name='otp_login'),
    path('redirect/', views.RedirectPageView.as_view(), name='redirect'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path(
        'profile/edit/<username>/',
        views.ProfileUpdateView.as_view(),
        name='edit_profile',
    ),
    path('edit-level/<username>/', views.LevelUpdateView.as_view(), name='edit_level'),
    path(
        'callback/edit/<username>/',
        CallbackURLEdit.as_view(),
        name='api_viewer_callback',
    ),
]


urlpatterns += client_urls
urlpatterns += super_and_root_urls
urlpatterns += support_urls
urlpatterns += onboard_user_urls
urlpatterns += supervisor_user_urls
urlpatterns += disbursement_setups_urls
urlpatterns += instant_urls
urlpatterns += password_handling_urls
urlpatterns += oauth2_provider_urls
urlpatterns += sessions_urls
urlpatterns += system_urls

utilities/urls.py
from django.urls import path

from .views import (BudgetUpdateView, IncreaseBalanceRequestView,
                    ListIncreaseBalanceRequestView, MerchantLimitUpdateView)

app_name = "utilities"

urlpatterns = [
    path(
        'budget/edit/<str:username>/', BudgetUpdateView.as_view(), name='budget_update'
    ),
    path(
        'budget/transfer-request/',
        IncreaseBalanceRequestView.as_view(),
        name='transfer_request',
    ),
    path(
        'budget/list-transfer-request/',
        ListIncreaseBalanceRequestView.as_view(),
        name='list_transfer_request',
    ),
    path(
        'merchant/limit/<username>/edit/',
        MerchantLimitUpdateView.as_view(),
        name='merchant_limit_edit',
    ),
]

instant_cashin/models/instant_budget.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import pre_save
from django.utils.translation import gettext_lazy as _

from core.models import AbstractTimeStamp


class Budget(AbstractTimeStamp):
    """
    Model for checking budget before executing disbursement
    """

    disburser = models.OneToOneField(
            get_user_model(),
            on_delete=models.CASCADE,
            related_name='budget',
            verbose_name=_("Disburser"),
            help_text=_("Before every cashin transaction, "
                        "amount to be disbursed will be validated against checker's budget limit")
    )
    max_amount = models.IntegerField(_("Max Allowed Amount"), default=0, null=False, blank=False)
    disbursed_amount = models.IntegerField(_("Disbursed Amount"), default=0, null=False, blank=False)

    class Meta:
        verbose_name = "Allowed Budget"
        verbose_name_plural = "Allowed Budgets"
        get_latest_by = "-updated_at"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.disburser.username} Budget"

    def within_threshold(self, amount_to_be_disbursed):
        """
        Check if the amount to be disbursed plus the previously disbursed amount won't exceed the max_amount
        :param amount_to_be_disbursed: Amount to be disbursed at the currently running transaction
        :return: True/False
        """
        new_amount = self.disbursed_amount + amount_to_be_disbursed

        if not new_amount <= self.max_amount:
            return False
        return True

    def update_disbursed_amount(self, amount):
        """
        Update the total disbursement amount at each successful transaction
        :param amount: the amount to be disbursed
        :return: True/False
        """
        if not self.within_threshold(amount):
            return False

        self.disbursed_amount += amount
        self.save()
        return True


def budget_pre_save_receiver(instance, *args, **kwargs):
    pass

templates/instant_cashin/add_member.html
{% extends 'base_form_singlepage.html' %}
{% load i18n %}
{% load static %}
{% load custom_tags %}

{% block title %} {{ page_title }} {% endblock %}

{% block gentellacss %}
  <link href="{% static 'gentella/iCheck/skins/flat/green.css' %}" rel="stylesheet">
{% endblock gentellacss %}

{% block form %}
  <form action="." method="POST">
    {% csrf_token %}
    <h3>{{ form_title }}</h3>
    <div>
      {% for field in form.visible_fields %}
        <div class="form-group">
          <div class="col-xs-12">
            <div class="">
              {{ field | add_class:'form-control'}}
              {{ field.errors.as_ul }}
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    <div class="clearfix"></div>
    <br/>

    <div>
      <a class="reset_pass" href="{% url 'data:main_view' %}">{% trans 'Back' %}</a>
      <input class="btn btn-default submit" type="submit" value="{% trans 'Create' %}">
    </div>

    <div class="clearfix"></div>
    <div class="separator">
      <div class="clearfix"></div>
      <br/>
    </div>
  </form>
{% endblock form %}

{% block script %}
  <script src="{% static 'gentella/bootstrap.min.js' %}"></script>
  <script src="{% static 'gentella/icheck.min.js' %}"></script>
{% endblock script %}

templates/instant_cashin/admin_home.html
{% extends 'new_base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Orange Pending Transactions' %}{% endblock title %}

{% block body %}
    {% if not instant_transactions %}
      <div class="well upload-nav col-xs-12">
        <strong style="margin-top: 15px;">{% trans 'No pending Orange transactions' %}</strong>
      </div>
    {% else %}
        {% include 'instant_cashin/pending_orange_trx_list.html' with orange_pending_transactions=instant_transactions %}
    {% endif %}
{% endblock body %}

{% block script %}
<script>

    $(".export-pending").click(function () {
      var $row = $(this).closest("tr");                   // Find the row
      var $day_selected = $row.find("#day_value").text(); // Find the text
      $.ajax({
        type: 'GET',
        url: "{% url 'instant_cashin:download' %}" + '?date=' + $day_selected,
        success: function (data, text, xhr) {
          $('#success-alert-msg').show()
        }
      });
    });

</script>
{% endblock script %}

templates/instant_cashin/auth_keys.html
{% extends 'new_base.html' %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load custom_tags %}
{% block customcss %}
<style>
    .checker-keys {
      display: inline-block;
      word-wrap: break-word;
      margin-left: 10px;
      width: -webkit-fill-available;
    }
  </style>
{% endblock %}
{% block title %}{{ oauth2_app.user.username }} {% trans 'Auth Keys' %}{% endblock %}
{% block body %}
  <div class="page-title">
    <div class="title_left">
      <h3>{{ oauth2_app.user.username }} {% trans 'User Authorization Keys' %}</h3>
    </div>
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <ul class="list-group">
              <li class="list-group-item">
                <div class="row">
                  <div class="col-md-2 col-sm-2 col-xs-2">
                    <label style="font-size: 16px;">{% trans 'Client ID:' %}</label>
                  </div>
                  <div class="col-md-10 col-sm-10 col-xs-10">
                    <p class="checker-keys">
                      {% if oauth2_app %}
                        {{ oauth2_app.client_id }}
                      {% else %}
                        No client ID for this user
                      {% endif %}
                    </p>
                  </div>
                </div>
              </li>

              <li class="list-group-item">
                <div class="row">
                  <div class="col-md-2 col-sm-2 col-xs-2">
                    <label style="font-size: 16px;">{% trans 'Client Secret:' %}</label>
                  </div>
                  <div class="col-md-10 col-sm-10 col-xs-10">
                    <p class="checker-keys">
                      {% if oauth2_app %}
                        {{ oauth2_app.client_secret}}
                      {% else %}
                        No client secret for this user
                      {% endif %}
                    </p>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

  </div>
{% endblock %}

templates/instant_cashin/banks_transactions.html
{% load i18n %}
{% load banks_tags i18n %}

<div class="x_content">
  <table class="table table-bordered" id="transaction-table">
    <thead>
    <tr>
      <th class="trxTableHeader">{% trans 'Transaction ID' %}</th>
      <th class="trxTableHeader">{% trans 'Recipient' %}</th>
      <th class="trxTableHeader">{% trans 'Amount' %}</th>
      <th class="trxTableHeader">{% trans 'Fees' %}</th>
      <th class="trxTableHeader">{% trans 'Vat' %}</th>
      <th class="trxTableHeader">{% trans 'Status' %}</th>
      <th class="trxTableHeader">{% trans 'Updated At' %}</th>
    </tr>
    </thead>
    <tbody>
    {% for trx in transactions %}
      <tr data-id="{{ trx.uid }}"
          data-creditor_name="{{ trx.recipient_name }}"
          data-creditor_account_number="{{ trx.anon_recipient }}"
          data-creditor_bank_name="{{ trx.creditor_bank_name }}"
          data-amount="{{ trx.amount }}"
          data-status="{{ trx.status_choice_verbose }}"
          data-status_code="{{ trx.transaction_status_code }}"
          data-updated_at="{{ trx.updated_at }}"
          data-created_at="{{ trx.created_at }}"
          data-status_description="{{ trx.transaction_status_description }}"
          class="row-hover"
          data-href="#">
        <td>{{ trx.uid }}</td>
        <td>{{ trx.anon_recipient }}</td>
        <td>{{ trx.amount }}</td>
        <td>{{ trx.fees }}</td>
        <td>{{ trx.vat }}</td>
        <td>{{ trx.status_choice_verbose }}</td>
        <td>{{ trx.updated_at }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <ul class="pagination">
  {% if transactions.has_previous %}
      <li>
        <a href="?page={{ transactions.previous_page_number }}&{{query_string}}">
          <i class="fa fa-chevron-left" aria-hidden="true"></i>
        </a>
      </li>
  {% else %}
      <li class="disabled"><span><i class="fa fa-chevron-left" aria-hidden="true"></i></span></li>
  {% endif %}

  {% if transactions.number|add:'-4' > 1 %}
      <li><a href="?page={{ transactions.number|add:'-5' }}&{{query_string}}">&hellip;</a></li>
  {% endif %}

  {% for i in transactions.paginator.page_range %}
      {% if transactions.number == i %}
          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% elif i > transactions.number|add:'-5' and i < transactions.number|add:'5' %}
          <li><a href="?page={{ i }}&{{query_string}}">{{ i }}</a></li>
      {% endif %}
  {% endfor %}

  {% if transactions.paginator.num_pages > transactions.number|add:'4' %}
      <li><a href="?page={{ transactions.number|add:'5' }}&{{query_string}}">&hellip;</a></li>
  {% endif %}

  {% if transactions.has_next %}
      <li>
        <a href="?page={{ transactions.next_page_number }}&{{query_string}}">
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
      </li>
  {% else %}
      <li class="disabled"><span><i class="fa fa-chevron-right" aria-hidden="true"></i></span></li>
  {% endif %}
  </ul>
  <style>
  .pagination > li > span {
    width: 33px;
  }
  </style>
  {% include 'pagination.html' %}
</div>

templates/instant_cashin/sidebar.html
{% load static %}
{% load i18n %}

<div class="left_col scroll-view">

  {% include "sidebar_logo.html" %}

  {# sidebar menu #}
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <ul class="nav side-menu">
        <li><a href="{% url 'disbursement:home_root' %}"><i class="fa fa-home"></i>{% trans 'Home' %}</a></li>
        <li><a href="{% url 'instant_cashin:wallets_trx_list' %}"><i class="fa fa-exchange"></i>{% trans 'Wallets Transactions' %}</a></li>
        <li><a href="{% url 'instant_cashin:banks_trx_list' %}"><i class="fa fa-exchange"></i>{% trans 'Banks Transactions' %}</a></li>

        {% if request.user.is_root %}
          <li><a><i class="fa fa-users"></i>{% trans 'Members' %}<span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a>{% trans 'Add member' %}<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="{% url 'users:add_viewer' %}">{% trans 'Viewer' %}</a></li>
                  <li><a href="{% url 'users:add_api_checker' %}">{% trans 'API Checker' %}</a></li>
                </ul>
              </li>
              <li><a href="{% url 'users:members' %}">{% trans 'All members' %}</a></li>
            </ul>
          </li>
        {% endif %}
        {% if request.user.has_access_to_topUp_balance %}
          <li>
            <a>
              <img style="width: 19px;margin-right: 6px;" src="{% static 'img/money_plus.png' %}">{% trans 'Topup balance' %}
              <span class="fa fa-chevron-down"></span>
            </a>
            <ul class="nav child_menu">
              <li><a href="{% url 'utilities:transfer_request' %}">{% trans 'Add topup balance Request' %}</a></li>
              <li><a href="{% url 'utilities:list_transfer_request' %}">{% trans 'All topup balance Requests' %}</a></li>
            </ul>
          </li>
        {% endif %}
        <li><a href="{% url 'docs:instant_docs' path='' %}" rel="noopener" target="_blank"><i class="fa fa-book"></i>{% trans 'API Documentation'%}</a></li>
        <li><a href="{% url 'disbursement:balance_inquiry' username=request.user.root.username %}"><i class="fa fa-suitcase"></i>{% trans 'Balance Inquiry' %}</a></li>
        <li><a href="{% url 'utilities:merchant_limit_edit' request.user.username %}"><i class="fa fa-gear"></i>{% trans 'Merchant Limit'%}</a></li>
        <li><a href="{% url 'users:profile' request.user.username %}"><i class="fa fa-user"></i>{% trans 'Profile' %}</a></li>
        <li><a href="{% url 'users:api_viewer_callback' request.user.username %}"><i class="fa fa-sliders"></i>{% trans 'Callback URL'%}</a></li>
        <li><a href="{% url 'users:session_list' %}"><i class="fa fa-clock-o"></i>{% trans 'Active Sessions' %}</a></li>
      </ul>
    </div>
  </div>
  {# End of Sidebar menu #}

</div>