data/urls.py
from django.urls import path

from data import views

app_name = 'data'

urlpatterns = [
    path('', views.redirect_home, name='main_view'),
    path('collection/', views.collection_home, name='collection_home'),
    path(
        'disbursement/e-wallets/',
        views.DisbursementHomeView.as_view(),
        name='e_wallets_home',
    ),
    path(
        'disbursement/bank-wallets/',
        views.BanksHomeView.as_view(),
        name='bank_wallets_home',
    ),
    path(
        'disbursement/bank-cards/',
        views.BanksHomeView.as_view(),
        name='bank_cards_home',
    ),
    path('delete/(<pk>/', views.FileDeleteView.as_view(), name='file_delete'),
    path('documents/<doc_id>/', views.document_view, name='doc_viewer'),
    path('download_doc/<doc_id>/', views.doc_download, name='download_doc'),
    path('format/list', views.FormatListView.as_view(), name='list_format'),
    path(
        'document/collection/<pk>/',
        views.RetrieveCollectionData.as_view(),
        name='doc_collection_detail',
    ),
    path(
        'transaction/report-problem/<trx_type>/<trx_id>/',
        views.ReportProblemView.as_view(),
        name='report_problem',
    ),
]

disbursement/urls.py
from django.urls import path

from .views import (
    AgentsListView, BalanceInquiry,
    SuperAdminAgentsSetup, disburse, DisbursementDocTransactionsView,
    download_failed_validation_file, ExportClientsTransactionsReportPerSuperAdmin,
    failed_disbursed_for_download, SingleStepTransactionsView,
    DownloadSampleSheetView, download_exported_transactions, HomeView,
    DisbursementDataListView, OrangeBankWalletListView, BanksListView,CreatePaymentLink, DisbursePaymentLink
)


app_name = 'disbursement'

client_urls = [
    path('agents/', AgentsListView.as_view(), name='agents_list'),
    path('home/', HomeView.as_view(), name='home_root'),
    path('home/portal-transactions/', DisbursementDataListView.as_view(), name='vf_et_aman_list'),
    path('home/portal-transactions-orange/', OrangeBankWalletListView.as_view(), name='orange_bank_wallet_list'),
    path('home/portal-transactions-banks/', BanksListView.as_view(), name='banks_list'),
    path('budget/inquiry/<str:username>/', BalanceInquiry.as_view(), name='balance_inquiry'),
    path('client/creation/agents/<token>/', SuperAdminAgentsSetup.as_view(), name='add_agents'),
]

urlpatterns = [
    path('disburse/single-step/', SingleStepTransactionsView.as_view(), name='single_step_list_create'),
    path('disburse_call/<doc_id>/', disburse, name='disburse'),
    path('disburse/export-sample-file/', DownloadSampleSheetView.as_view(), name='export_sample_file'),
    path('disburse/report/<doc_id>/', DisbursementDocTransactionsView.as_view(), name='disbursed_data'),
    path('disburse/export_failed_download/<doc_id>/', failed_disbursed_for_download, name='download_failed'),
    path('disburse/download_exported_transactions/', download_exported_transactions, name='download_exported'),
    path(
            'disburse/export-clients-transactions-report/',
            ExportClientsTransactionsReportPerSuperAdmin.as_view(),
            name='export_clients_transactions_report'
    ),
    path('disburse/export_failed_validation_download/<doc_id>/',
         download_failed_validation_file, name='download_validation_failed'),
    path('create/payment-link/', CreatePaymentLink.as_view(), name='create_payment_link'),
    path('disburse/payment/link/<payment_token>/', DisbursePaymentLink.as_view(), name='disburse_payment_link')
]

urlpatterns += client_urls

docs/urls.py
from django.urls import re_path, path
from django.views.generic import TemplateView

from .views import serve_docs


app_name = 'docs'


urlpatterns = [
    path('docs/swagger-ui/', TemplateView.as_view(
            template_name='instant_cashin/swagger_api_docs.html',
            extra_context={'schema_url': 'openapi-schema'}
        ), name='swagger-ui'),
    re_path(r'^docs/(?P<path>.*)$', serve_docs, name='instant_docs'),
]

instant_cashin/urls.py
from django.urls import path

from .views import BankTransactionsListView, InstantTransactionsListView


app_name = 'instant_cashin'

urlpatterns = [
    path('instant-transactions/wallets/', InstantTransactionsListView.as_view(), name='wallets_trx_list'),
    path('instant-transactions/banks/', InstantTransactionsListView.as_view(), name='banks_trx_list'),
]

users/urls.py
# -*- coding: utf-8 -*-

from django.contrib.auth import views as django_auth_views
from django.urls import path
from oauth2_provider import views as oauth2_views

from payouts.views import no_agent_error_view
from users.views.main_views import CallbackURLEdit

from . import views

app_name = 'users'


client_urls = [
    path('clients/', views.Clients.as_view(), name='clients'),
    path('client/creation/', views.SuperAdminRootSetup.as_view(), name='add_client'),
    path(
        'client/delete/<str:username>/',
        views.SuperAdminCancelsRootSetupView.as_view(),
        name='delete_client',
    ),
    # 'Adding agents' -url- to the clients is at the disb. app urlpatterns
    path(
        'client/fees-setup/<token>/', views.ClientFeesSetup.as_view(), name='add_fees'
    ),
    path(
        'fees-profile/',
        views.SuperAdminFeesProfileTemplateView.as_view(),
        name='super_fees_profile',
    ),
    path(
        'client/fees-setup/edit/<str:username>/',
        views.CustomClientFeesProfilesUpdateView.as_view(),
        name='update_fees',
    ),
    path(
        'client/fees-setup/update/<str:username>/',
        views.ClientFeesUpdate.as_view(),
        name='update_fees_profile',
    ),
    path('client/toggle/', views.toggle_client, name='toggle'),
]

super_and_root_urls = [
    path('members/', views.Members.as_view(), name='members'),
    path('user/delete/', views.UserDeleteView.as_view(), name='delete'),
    path('settings/branding/', views.EntityBranding.as_view(), name='entity_branding'),
]

support_urls = [
    path('support/home/', views.SupportHomeView.as_view(), name='support_home'),
    path(
        'support/documents/<username>/',
        views.DocumentsForSupportListView.as_view(),
        name='documents_list',
    ),
    path(
        'support/documents/<username>/<doc_id>/',
        views.DocumentForSupportDetailView.as_view(),
        name='doc_detail',
    ),
    path('support/', views.SupportUsersListView.as_view(), name='support'),
    path(
        'support/creation/',
        views.SuperAdminSupportSetupCreateView.as_view(),
        name='add_support',
    ),
    path(
        'support/clients/',
        views.ClientsForSupportListView.as_view(),
        name='support_clients_list',
    ),
    path(
        'support/clients/Credentials',
        views.OnboardingNewInstantAdmin.as_view(),
        name='support_clients_credentials',
    ),
    path(
        'support/clients/Credentials/<client_id>',
        views.ClientCredentialsDetails.as_view(),
        name='support_clients_credentials_details',
    ),
]

onboard_user_urls = [
    path(
        'onboard-user/home/',
        views.OnbooardUserHomeView.as_view(),
        name='onboard_user_home',
    ),
    path('onboard-user/', views.OnboardUsersListView.as_view(), name='onboard_user'),
    path(
        'onboard-user/creation/',
        views.SuperAdminOnboardSetupCreateView.as_view(),
        name='add_onboard_user',
    ),
]

supervisor_user_urls = [
    path(
        'supervisor/home/',
        views.SupervisorUserHomeView.as_view(),
        name='supervisor_home',
    ),
    path('supervisor/', views.SupervisorUsersListView.as_view(), name='supervisor'),
    path(
        'supervisor/creation/',
        views.SuperAdminSupervisorSetupCreateView.as_view(),
        name='add_supervisor_user',
    ),
    path(
        'supervisor/reactivate_support_user',
        views.SupervisorReactivateSupportView.as_view(),
        name='reactivate_support_user',
    ),
]

disbursement_setups_urls = [
    path(
        'setting-up/disbursement-pin',
        views.PinFormView.as_view(),
        name='setting-disbursement-pin',
    ),
    path(
        'setting-up/disbursement-makers',
        views.MakerFormView.as_view(),
        name='setting-disbursement-makers',
    ),
    path(
        'setting-up/disbursement-levels',
        views.LevelsFormView.as_view(),
        name='setting-disbursement-levels',
    ),
    path(
        'setting-up/disbursement-checkers',
        views.CheckerFormView.as_view(),
        name='setting-disbursement-checkers',
    ),
    path(
        'setting-up/disbursement-formats',
        views.CategoryFormView.as_view(),
        name='setting-disbursement-formats',
    ),
    path('members/maker/add/', views.AddMakerView.as_view(), name='add_maker'),
    path('members/checker/add/', views.AddCheckerView.as_view(), name='add_checker'),
    path('levels/', views.LevelsView.as_view(), name='levels'),
    path('change_pin/', views.change_pin_view, name='change_pin'),
    path(
        'vodafone/change-pin/',
        views.vodafone_change_pin_view.as_view(),
        name='vodafone_change_pin',
    ),
]

instant_urls = [
    path('members/viewer/add/', views.ViewerCreateView.as_view(), name='add_viewer'),
    path(
        'members/api-checker/add/',
        views.APICheckerCreateView.as_view(),
        name='add_api_checker',
    ),
]

password_handling_urls = [
    path('change_password/<user>/', views.change_password, name="change_password"),
    path(
        'forgot-password/', views.ForgotPasswordView.as_view(), name="forgot_password"
    ),
    path('password/reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path(
        'password/reset/done/',
        django_auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'password/reset/<uidb64>/<token>/',
        django_auth_views.PasswordResetConfirmView.as_view(
            success_url='/', template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'password/done/',
        django_auth_views.PasswordResetCompleteView.as_view(),
        {'extra_context': {'login_url': '/user/login'}},
        name='password_reset_complete',
    ),
]

oauth2_provider_urls = [
    path("api/secure/o/token/", oauth2_views.TokenView.as_view(), name="oauth2_token"),
    path(
        "oauth2/keys/<username>/",
        views.OAuth2ApplicationDetailView.as_view(),
        name="oauth2_detail",
    ),
]

sessions_urls = [
    path('sessions/', views.SessionListView.as_view(), name='session_list'),
    path(
        'sessions/other/delete/',
        views.SessionDeleteOtherView.as_view(),
        name='session_delete_other',
    ),
    path(
        'sessions/<str:pk>/delete/',
        views.SessionDeleteView.as_view(),
        name='session_delete',
    ),
]

system_urls = [
    path(
        'creation/admin/<token>/',
        views.OnboardingNewMerchant.as_view(),
        name='creation_admin',
    ),
]

urlpatterns = [
    path('user/login/', views.login_view, name='user_login_view'),
    path('user/logout/', views.ourlogout, name='logout'),    
    path('user/no-agent/', no_agent_error_view, name='no_agent_error'),
    path('account/token/', views.OTPLoginView.as_view(), name='otp_login'),
    path('redirect/', views.RedirectPageView.as_view(), name='redirect'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path(
        'profile/edit/<username>/',
        views.ProfileUpdateView.as_view(),
        name='edit_profile',
    ),
    path('edit-level/<username>/', views.LevelUpdateView.as_view(), name='edit_level'),
    path(
        'callback/edit/<username>/',
        CallbackURLEdit.as_view(),
        name='api_viewer_callback',
    ),
]


urlpatterns += client_urls
urlpatterns += super_and_root_urls
urlpatterns += support_urls
urlpatterns += onboard_user_urls
urlpatterns += supervisor_user_urls
urlpatterns += disbursement_setups_urls
urlpatterns += instant_urls
urlpatterns += password_handling_urls
urlpatterns += oauth2_provider_urls
urlpatterns += sessions_urls
urlpatterns += system_urls

users/models/support.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import gettext_lazy as _

from .base_user import User, UserManager


class SupportManager(UserManager):
    """
    Manager for support user
    """

    def get_queryset(self):
        return super().get_queryset().filter(user_type=8)

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('user_type', 8)
        return self._create_user(username, email, password, **extra_fields)


class SupportUser(User):
    """
    Support/Customer care user who can view on-boarded entities/roots or on-board entities.
    """

    objects = SupportManager()

    class Meta:
        proxy = True


class SupportSetup(models.Model):
    """
    Support Setup model to link and save the state of the support user setups by super admin
    """

    support_user = models.OneToOneField(
            SupportUser,
            on_delete=models.CASCADE,
            related_name='my_setups',
            verbose_name=_('Support User')
    )
    user_created = models.ForeignKey(
            'users.SuperAdminUser',
            on_delete=models.CASCADE,
            related_name='support_setups',
            verbose_name=_('Super Admin User')
    )
    supervisor = models.ForeignKey(
            'users.SupervisorUser',
            on_delete=models.SET_NULL,
            related_name='my_support_setups',
            verbose_name=_('Supervisor User'),
            null=True
    )
    can_onboard_entities = models.BooleanField(default=False, verbose_name=_('Can On-board Entities?'))

    class Meta:
        ordering = ['-id']

    def __str__(self):
        "String representation of each support setup object"
        return f'{self.user_created} setup for {self.support_user}'

templates/support/clients.html
{% extends 'new_base.html' %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load custom_tags %}

{% block title %} {% trans 'Clients' %} {% endblock title %}
{% block gentellacss %}
  <!-- Datatables -->
  <link href="{% static 'gentella/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'gentella/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'gentella/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'gentella/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'gentella/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/transaction_details.css' %}" rel="stylesheet">

  <style>
    #clientDetailsDataLeft li span, #clientDetailsDataLast li span {
      width: 100px;
    }
  </style>
{% endblock %}

{% block body %}
  <!-- page content -->
  <div class="col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>{% trans 'All Clients' %}</h3>
        </div>
        <div class="title_right">
          <form action="." method="get">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-{{'right'|invert_dir:LANGUAGE_CODE}} top_search">
              <div class="input-group">

                <input type="text" class="form-control" name="search" value="{{ search }}" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-default" type="submit" value="search">{% trans 'Go!' %}</button>
                </span>
              </div>
            </div>
          </form>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_content">
              <table class="table table-bordered" id="transaction-table">
                <thead>
                <tr>
                  <th>{% trans 'Image' %}</th>
                  <th>{% trans 'Username' %}</th>
                  <th>{% trans 'Email' %}</th>
                  <th>{% trans 'Status' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for user in clients %}
                  <tr data-full_name="{{ user.client.get_full_name}}"
                      data-username="{{ user.client.username }}"
                      data-email="{{ user.client.email }}"
                      data-phone="{{ user.client.mobile_no }}"
                      data-about="{{ user.client.title }}"
                      data-status="{% if user.is_active %} {% trans 'Active' %} {% else %} {% trans 'InActive' %} {% endif %}"

                      {% if request.user.is_instant_model_onboarding %}
                        data-integration_wallets_trx="{% url 'instant_cashin:wallets_trx_list' %}?client={{ user.client.username }}"
                        data-integration_banks_trx="{% url 'instant_cashin:banks_trx_list' %}?client={{ user.client.username }}"
                      {% else %}
                        data-formats="{% url 'data:list_format' %}?admin={{ user.client.username }}"
                        data-document_list="{% url 'users:documents_list' username=user.client.username %}"
                      {% endif %}

                      {% if user.client.is_vodafone_default_onboarding %}
                        data-fees_profile="{{user.get_fees}}"
                        data-agent_list="{% url 'disbursement:agents_list' %}?admin={{ user.client.username }}"
                      {% else %}
                        data-current_balance="{{ user.client.budget.current_balance }}"
                      {% endif %}

                      {% if user.client.is_accept_vodafone_onboarding %}
                        data-single_step_trxs="{% url 'disbursement:single_step_list_create' %}?admin_hierarchy={{ user.client.hierarchy }}"
                      {% endif %}
                      class="row-hover">
                    <td style="text-align: center;"><img width="50" height="50" src="{{ user.client.avatar_thumbnail.url }}" alt="" class="img-circle"></td>
                    <td>{{ user.client.username }}</td>
                    <td>{{ user.client.email }}</td>
                    <td>
                      {% if user.is_active %}
                        {% trans 'Active' %}
                      {% else %}
                        {% trans 'InActive' %}
                      {% endif %}
                    </td>
                  </tr>
                {% empty %}
                  <h4 class="text-center">{% trans 'No clients are set here...' %}</h4>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

    {# client details #}
    <div id="clientDetails" style="display: none;" class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2 class="font-13 m-b-30" style="font-weight: bolder;">{% trans 'Client Details' %}</h2>
            <div class="clearfix"></div>
          </div>

          <div class="x_content">
            <div class="row">
              <div class="col-md-6 col-sm-6 col-xs-6">
                <ul id="clientDetailsDataLeft">
                </ul>
              </div>
              <div class="col-md-6 col-sm-6 col-xs-6">
                <ul id="clientDetailsDataRight">
                </ul>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <ul id="clientDetailsDataLast">
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {# End of client details #}
  </div>
  <!-- /page content -->
{% endblock body %}

{% block script %}
<!-- Datatables -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="{% static 'gentella/vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'gentella/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<script src="{% static 'gentella/vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'gentella/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
<script src="{% static 'gentella/vendors/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static 'gentella/vendors/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'gentella/vendors/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'gentella/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
<script src="{% static 'gentella/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
<script src="{% static 'gentella/vendors/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'gentella/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
<script src="{% static 'gentella/vendors/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
<script>
    var table = $('#transaction-table').DataTable({
    "bLengthChange" : false,
  });
  
  var buttons = new $.fn.dataTable.Buttons( table, {
        buttons: [
          {
                extend: 'copy',
                text : "{% trans 'Copy' %}",
                exportOptions: {
                    charSet: "utf-8",
                }
            },
            {
                extend: 'print',
                text : "PDF",
            },
            {
                extend: 'excelHtml5',
                text : "{% trans 'Export' %}",
                
                customize: function( xlsx ) {

                  var sheet = xlsx.xl.worksheets['sheet1.xml'];
                  $('row c[r^="A"]', sheet).attr( 's', '0' );
				       }
            }
        ]
    });
  
  table.buttons( 0, null ).container().prependTo(
        table.table().container()
    );

  let empty_row = $('.dataTables_empty');
  if (empty_row) {
    empty_row.parent().attr('id', 'empty_row');
  }
    
  </script>
<script>
    $('#transaction-table tbody').on('click', 'tr:not(#empty_row)', function () {
      if ($(this).hasClass('selected')) {
        $(this).removeClass('selected');
        $("#clientDetails").slideUp().fadeOut();
      }
      else {
        $('tr.selected').removeClass('selected');
        $(this).addClass('selected');
        let ulLeft = $('#clientDetailsDataLeft');
        let ulRight = $('#clientDetailsDataRight');
        let ulLast = $('#clientDetailsDataLast');
        let appendedTagsLeft = '';
        let appendedTagsRight = '';
        let appendedTagsLast = '';
        // add data to ul left
        let full_name = $(this).data('full_name');
        appendedTagsLeft += `<li><span>{% trans 'Full Name' %}</span><strong>: </strong>${full_name}</li>`;

        let username = $(this).data('username');
        appendedTagsLeft += `<li><span>{% trans 'Username' %}</span><strong>: </strong>${username}</li>`;

        let email = $(this).data('email');
        appendedTagsLeft += `<li><span>{% trans 'Email' %}</span><strong>: </strong>${email}</li>`;

        let phone = $(this).data('phone');
        appendedTagsLeft += `<li><span>{% trans 'Mobile Number' %}</span><strong>: </strong>${phone}</li>`;

        // add data to ul right
        let status = $(this).data('status');
        appendedTagsRight += `<li><span>{% trans 'Status' %}</span><strong>: </strong>${status}</li>`;

        let agent_list = $(this).data('agent_list');
        let current_balance = $(this).data('current_balance');
        if (agent_list && !current_balance) {
          appendedTagsRight += `<li><span>{% trans 'Agents' %}</span><strong>: </strong><a href=${agent_list} >{% trans 'Agents List' %}</a></li>`
        } else {
          appendedTagsRight += `<li><span>{% trans 'Current Balance' %}</span><strong>: </strong>${current_balance} EG</li>`;
        }

        {% if request.user.is_instant_model_onboarding %}
          let integration_wallets_trx = $(this).data('integration_wallets_trx');
          let integration_banks_trx = $(this).data('integration_banks_trx');
          appendedTagsRight += `<li><span>{% trans 'Wallets Transactions' %}</span><strong>: </strong><a href=${integration_wallets_trx} >{% trans 'Transactions List' %}</a></li>`;
          appendedTagsRight += `<li><span>{% trans 'Banks Transactions' %}</span><strong>: </strong><a href=${integration_banks_trx} >{% trans 'Transactions List' %}</a></li>`;
        {% else %}
          let formats = $(this).data('formats');
          let document_list = $(this).data('document_list');
          appendedTagsRight += `<li><span>{% trans 'Formats' %}</span><strong>: </strong><a href=${formats} >{% trans 'Formats' %}</a></li>`;
          appendedTagsRight += `<li><span>{% trans 'Disbursement Documents List' %}</span><strong>: </strong><a href=${document_list} >{% trans 'Documents' %}</a></li>`;
          {% if request.user.is_accept_vodafone_onboarding %}
            let single_step_trxs = $(this).data('single_step_trxs');
            appendedTagsRight += `<li><span>{% trans 'Single Step Transactions' %}</span><strong>: </strong><a href=${single_step_trxs} >{% trans 'Transactions' %}</a></li>`;
          {% endif %}
        {% endif %}
        {% if request.user.is_vodafone_default_onboarding %}
          let fees_profile = $(this).data('fees_profile');
          appendedTagsRight += `<li><span>{% trans 'Fees Profile' %}</span><strong>: </strong>${fees_profile}</li>`;
        {% endif %}

        ulLeft.empty();
        ulLeft.append(appendedTagsLeft);

        ulRight.empty();
        ulRight.append(appendedTagsRight);

        let about = $(this).data('about');
        appendedTagsLast += `<li><span>{% trans 'About' %}</span><strong>: </strong>${about}</li>`;
        ulLast.empty();
        ulLast.append(appendedTagsLast);

        $("#clientDetails").slideDown();
        $('html,body').animate({
          scrollTop: $("#clientDetails").offset().top
        }, 'slow');
     }
    });
  </script>
{% endblock %}

templates/support/home.html
{% extends 'new_base.html' %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load custom_tags %}

{% block title %} {% trans 'Home' %} {% endblock title %}

{% block body %}
  <div class="well upload-nav col-xs-12">
    <strong style="margin-top: 15px;">{% trans 'Welcome home ...' %}</strong>
  </div>
{% endblock body %}

templates/support/sidebar.html
{% load static %}
{% load i18n %}

<div class="left_col scroll-view">

  {% include "sidebar_logo.html" %}

  {# sidebar menu #}
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <ul class="nav side-menu">
        <li><a href="{% url 'users:support_clients_list' %}"><i class="fa fa-users"></i>{% trans 'All Clients' %}</a></li>
        <li><a href="{% url 'docs:instant_docs' path='' %}" rel="noopener" target="_blank"><i class="fa fa-book"></i>{% trans 'API Documentation'%}</a></li>
        {% if request.user.my_setups.can_onboard_entities and request.user.is_instant_model_onboarding %}
          <li><a href="{% url 'users:support_clients_credentials' %}"><i class="fa fa-lock"></i>{% trans 'Clients Credentials'%}</a></li>
        {% endif %}
        <li><a href="{% url 'users:session_list' %}"><i class="fa fa-clock-o" ></i>{% trans 'Active Sessions' %}</a></li>
        <li><a href="{% url 'users:profile' request.user.username %}"><i class="fa fa-user"></i>{% trans 'Profile' %}</a></li>
      </ul>
    </div>
  </div>
  {# End of Sidebar menu #}

</div>