data/urls.py
from django.urls import path

from data import views

app_name = 'data'

urlpatterns = [
    path('', views.redirect_home, name='main_view'),
    path('collection/', views.collection_home, name='collection_home'),
    path(
        'disbursement/e-wallets/',
        views.DisbursementHomeView.as_view(),
        name='e_wallets_home',
    ),
    path(
        'disbursement/bank-wallets/',
        views.BanksHomeView.as_view(),
        name='bank_wallets_home',
    ),
    path(
        'disbursement/bank-cards/',
        views.BanksHomeView.as_view(),
        name='bank_cards_home',
    ),
    path('delete/(<pk>/', views.FileDeleteView.as_view(), name='file_delete'),
    path('documents/<doc_id>/', views.document_view, name='doc_viewer'),
    path('download_doc/<doc_id>/', views.doc_download, name='download_doc'),
    path('format/list', views.FormatListView.as_view(), name='list_format'),
    path(
        'document/collection/<pk>/',
        views.RetrieveCollectionData.as_view(),
        name='doc_collection_detail',
    ),
    path(
        'transaction/report-problem/<trx_type>/<trx_id>/',
        views.ReportProblemView.as_view(),
        name='report_problem',
    ),
]

disbursement/urls.py
from django.urls import path

from .views import (
    AgentsListView, BalanceInquiry,
    SuperAdminAgentsSetup, disburse, DisbursementDocTransactionsView,
    download_failed_validation_file, ExportClientsTransactionsReportPerSuperAdmin,
    failed_disbursed_for_download, SingleStepTransactionsView,
    DownloadSampleSheetView, download_exported_transactions, HomeView,
    DisbursementDataListView, OrangeBankWalletListView, BanksListView,CreatePaymentLink, DisbursePaymentLink
)


app_name = 'disbursement'

client_urls = [
    path('agents/', AgentsListView.as_view(), name='agents_list'),
    path('home/', HomeView.as_view(), name='home_root'),
    path('home/portal-transactions/', DisbursementDataListView.as_view(), name='vf_et_aman_list'),
    path('home/portal-transactions-orange/', OrangeBankWalletListView.as_view(), name='orange_bank_wallet_list'),
    path('home/portal-transactions-banks/', BanksListView.as_view(), name='banks_list'),
    path('budget/inquiry/<str:username>/', BalanceInquiry.as_view(), name='balance_inquiry'),
    path('client/creation/agents/<token>/', SuperAdminAgentsSetup.as_view(), name='add_agents'),
]

urlpatterns = [
    path('disburse/single-step/', SingleStepTransactionsView.as_view(), name='single_step_list_create'),
    path('disburse_call/<doc_id>/', disburse, name='disburse'),
    path('disburse/export-sample-file/', DownloadSampleSheetView.as_view(), name='export_sample_file'),
    path('disburse/report/<doc_id>/', DisbursementDocTransactionsView.as_view(), name='disbursed_data'),
    path('disburse/export_failed_download/<doc_id>/', failed_disbursed_for_download, name='download_failed'),
    path('disburse/download_exported_transactions/', download_exported_transactions, name='download_exported'),
    path(
            'disburse/export-clients-transactions-report/',
            ExportClientsTransactionsReportPerSuperAdmin.as_view(),
            name='export_clients_transactions_report'
    ),
    path('disburse/export_failed_validation_download/<doc_id>/',
         download_failed_validation_file, name='download_validation_failed'),
    path('create/payment-link/', CreatePaymentLink.as_view(), name='create_payment_link'),
    path('disburse/payment/link/<payment_token>/', DisbursePaymentLink.as_view(), name='disburse_payment_link')
]

urlpatterns += client_urls

docs/urls.py
from django.urls import re_path, path
from django.views.generic import TemplateView

from .views import serve_docs


app_name = 'docs'


urlpatterns = [
    path('docs/swagger-ui/', TemplateView.as_view(
            template_name='instant_cashin/swagger_api_docs.html',
            extra_context={'schema_url': 'openapi-schema'}
        ), name='swagger-ui'),
    re_path(r'^docs/(?P<path>.*)$', serve_docs, name='instant_docs'),
]

users/urls.py
# -*- coding: utf-8 -*-

from django.contrib.auth import views as django_auth_views
from django.urls import path
from oauth2_provider import views as oauth2_views

from payouts.views import no_agent_error_view
from users.views.main_views import CallbackURLEdit

from . import views

app_name = 'users'


client_urls = [
    path('clients/', views.Clients.as_view(), name='clients'),
    path('client/creation/', views.SuperAdminRootSetup.as_view(), name='add_client'),
    path(
        'client/delete/<str:username>/',
        views.SuperAdminCancelsRootSetupView.as_view(),
        name='delete_client',
    ),
    # 'Adding agents' -url- to the clients is at the disb. app urlpatterns
    path(
        'client/fees-setup/<token>/', views.ClientFeesSetup.as_view(), name='add_fees'
    ),
    path(
        'fees-profile/',
        views.SuperAdminFeesProfileTemplateView.as_view(),
        name='super_fees_profile',
    ),
    path(
        'client/fees-setup/edit/<str:username>/',
        views.CustomClientFeesProfilesUpdateView.as_view(),
        name='update_fees',
    ),
    path(
        'client/fees-setup/update/<str:username>/',
        views.ClientFeesUpdate.as_view(),
        name='update_fees_profile',
    ),
    path('client/toggle/', views.toggle_client, name='toggle'),
]

super_and_root_urls = [
    path('members/', views.Members.as_view(), name='members'),
    path('user/delete/', views.UserDeleteView.as_view(), name='delete'),
    path('settings/branding/', views.EntityBranding.as_view(), name='entity_branding'),
]

support_urls = [
    path('support/home/', views.SupportHomeView.as_view(), name='support_home'),
    path(
        'support/documents/<username>/',
        views.DocumentsForSupportListView.as_view(),
        name='documents_list',
    ),
    path(
        'support/documents/<username>/<doc_id>/',
        views.DocumentForSupportDetailView.as_view(),
        name='doc_detail',
    ),
    path('support/', views.SupportUsersListView.as_view(), name='support'),
    path(
        'support/creation/',
        views.SuperAdminSupportSetupCreateView.as_view(),
        name='add_support',
    ),
    path(
        'support/clients/',
        views.ClientsForSupportListView.as_view(),
        name='support_clients_list',
    ),
    path(
        'support/clients/Credentials',
        views.OnboardingNewInstantAdmin.as_view(),
        name='support_clients_credentials',
    ),
    path(
        'support/clients/Credentials/<client_id>',
        views.ClientCredentialsDetails.as_view(),
        name='support_clients_credentials_details',
    ),
]

onboard_user_urls = [
    path(
        'onboard-user/home/',
        views.OnbooardUserHomeView.as_view(),
        name='onboard_user_home',
    ),
    path('onboard-user/', views.OnboardUsersListView.as_view(), name='onboard_user'),
    path(
        'onboard-user/creation/',
        views.SuperAdminOnboardSetupCreateView.as_view(),
        name='add_onboard_user',
    ),
]

supervisor_user_urls = [
    path(
        'supervisor/home/',
        views.SupervisorUserHomeView.as_view(),
        name='supervisor_home',
    ),
    path('supervisor/', views.SupervisorUsersListView.as_view(), name='supervisor'),
    path(
        'supervisor/creation/',
        views.SuperAdminSupervisorSetupCreateView.as_view(),
        name='add_supervisor_user',
    ),
    path(
        'supervisor/reactivate_support_user',
        views.SupervisorReactivateSupportView.as_view(),
        name='reactivate_support_user',
    ),
]

disbursement_setups_urls = [
    path(
        'setting-up/disbursement-pin',
        views.PinFormView.as_view(),
        name='setting-disbursement-pin',
    ),
    path(
        'setting-up/disbursement-makers',
        views.MakerFormView.as_view(),
        name='setting-disbursement-makers',
    ),
    path(
        'setting-up/disbursement-levels',
        views.LevelsFormView.as_view(),
        name='setting-disbursement-levels',
    ),
    path(
        'setting-up/disbursement-checkers',
        views.CheckerFormView.as_view(),
        name='setting-disbursement-checkers',
    ),
    path(
        'setting-up/disbursement-formats',
        views.CategoryFormView.as_view(),
        name='setting-disbursement-formats',
    ),
    path('members/maker/add/', views.AddMakerView.as_view(), name='add_maker'),
    path('members/checker/add/', views.AddCheckerView.as_view(), name='add_checker'),
    path('levels/', views.LevelsView.as_view(), name='levels'),
    path('change_pin/', views.change_pin_view, name='change_pin'),
    path(
        'vodafone/change-pin/',
        views.vodafone_change_pin_view.as_view(),
        name='vodafone_change_pin',
    ),
]

instant_urls = [
    path('members/viewer/add/', views.ViewerCreateView.as_view(), name='add_viewer'),
    path(
        'members/api-checker/add/',
        views.APICheckerCreateView.as_view(),
        name='add_api_checker',
    ),
]

password_handling_urls = [
    path('change_password/<user>/', views.change_password, name="change_password"),
    path(
        'forgot-password/', views.ForgotPasswordView.as_view(), name="forgot_password"
    ),
    path('password/reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path(
        'password/reset/done/',
        django_auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'password/reset/<uidb64>/<token>/',
        django_auth_views.PasswordResetConfirmView.as_view(
            success_url='/', template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'password/done/',
        django_auth_views.PasswordResetCompleteView.as_view(),
        {'extra_context': {'login_url': '/user/login'}},
        name='password_reset_complete',
    ),
]

oauth2_provider_urls = [
    path("api/secure/o/token/", oauth2_views.TokenView.as_view(), name="oauth2_token"),
    path(
        "oauth2/keys/<username>/",
        views.OAuth2ApplicationDetailView.as_view(),
        name="oauth2_detail",
    ),
]

sessions_urls = [
    path('sessions/', views.SessionListView.as_view(), name='session_list'),
    path(
        'sessions/other/delete/',
        views.SessionDeleteOtherView.as_view(),
        name='session_delete_other',
    ),
    path(
        'sessions/<str:pk>/delete/',
        views.SessionDeleteView.as_view(),
        name='session_delete',
    ),
]

system_urls = [
    path(
        'creation/admin/<token>/',
        views.OnboardingNewMerchant.as_view(),
        name='creation_admin',
    ),
]

urlpatterns = [
    path('user/login/', views.login_view, name='user_login_view'),
    path('user/logout/', views.ourlogout, name='logout'),    
    path('user/no-agent/', no_agent_error_view, name='no_agent_error'),
    path('account/token/', views.OTPLoginView.as_view(), name='otp_login'),
    path('redirect/', views.RedirectPageView.as_view(), name='redirect'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path(
        'profile/edit/<username>/',
        views.ProfileUpdateView.as_view(),
        name='edit_profile',
    ),
    path('edit-level/<username>/', views.LevelUpdateView.as_view(), name='edit_level'),
    path(
        'callback/edit/<username>/',
        CallbackURLEdit.as_view(),
        name='api_viewer_callback',
    ),
]


urlpatterns += client_urls
urlpatterns += super_and_root_urls
urlpatterns += support_urls
urlpatterns += onboard_user_urls
urlpatterns += supervisor_user_urls
urlpatterns += disbursement_setups_urls
urlpatterns += instant_urls
urlpatterns += password_handling_urls
urlpatterns += oauth2_provider_urls
urlpatterns += sessions_urls
urlpatterns += system_urls

utilities/urls.py
from django.urls import path

from .views import (BudgetUpdateView, IncreaseBalanceRequestView,
                    ListIncreaseBalanceRequestView, MerchantLimitUpdateView)

app_name = "utilities"

urlpatterns = [
    path(
        'budget/edit/<str:username>/', BudgetUpdateView.as_view(), name='budget_update'
    ),
    path(
        'budget/transfer-request/',
        IncreaseBalanceRequestView.as_view(),
        name='transfer_request',
    ),
    path(
        'budget/list-transfer-request/',
        ListIncreaseBalanceRequestView.as_view(),
        name='list_transfer_request',
    ),
    path(
        'merchant/limit/<username>/edit/',
        MerchantLimitUpdateView.as_view(),
        name='merchant_limit_edit',
    ),
]

templates/disbursement_sidebar.html
{% load static %}
{% load i18n %}
{% load custom_tags %}

<div class="left_col scroll-view">

  {% include "sidebar_logo.html" %}

  {# sidebar menu #}
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <ul class="nav side-menu">

        {% if request.user.is_vodafone_default_onboarding or request.user.is_vodafone_facilitator_onboarding or request.user.is_banks_standard_model_onboaring %}
          <li><a href="{% url 'data:e_wallets_home' %}"><i class="fa fa-files-o"></i>{% trans 'Disbursement Files' %}</a></li>
        {% elif request.user.is_accept_vodafone_onboarding %}
          <li><a><i class="fa fa-home"></i>{% trans 'Home' %}<span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="{% url 'disbursement:home_root' %}">{% trans 'Dashboard' %}</a></li>
              {% if not request.user.from_accept %}
                <li><a href="{% url 'disbursement:vf_et_aman_list' %}">{% trans 'Vodafone/Etisalat/Aman' %}</a></li>
                <li><a href="{% url 'disbursement:orange_bank_wallet_list' %}">{% trans 'Bank Wallets/Orange Cash' %}</a></li>
                <li><a href="{% url 'disbursement:banks_list' %}">{% trans 'Bank Accounts/Cards' %}</a></li>
              {% elif request.user.from_accept and request.user.allowed_to_be_bulk %}
                <li><a href="{% url 'disbursement:vf_et_aman_list' %}">{% trans 'Vodafone/Etisalat/Aman' %}</a></li>
                <li><a href="{% url 'disbursement:orange_bank_wallet_list' %}">{% trans 'Bank Wallets/Orange Cash' %}</a></li>
                <li><a href="{% url 'disbursement:banks_list' %}">{% trans 'Bank Accounts/Cards' %}</a></li>
              {% endif %}
            </ul>
          </li>
          {% if not request.user.from_accept %}
            <li><a href="{% url 'data:e_wallets_home' %}"><i class="fa fa-money"></i>{% trans 'Vodafone/Etisalat/Aman' %}</a></li>
            <li><a href="{% url 'data:bank_wallets_home' %}">
              <img style="width: 20px;margin-{{'right'|invert_dir:LANGUAGE_CODE}}: 6px;margin-bottom: 9px;" src="{% static 'img/wallet_money.png' %}">{% trans 'Bank Wallets/Orange Cash' %}</a></li>
            <li><a href="{% url 'data:bank_cards_home' %}"><i class="fa fa-credit-card"></i>{% trans 'Bank Accounts/Cards' %}</a></li>
          {% elif request.user.from_accept and request.user.allowed_to_be_bulk %}
            <li><a href="{% url 'data:e_wallets_home' %}"><i class="fa fa-money"></i>{% trans 'Vodafone/Etisalat/Aman' %}</a></li>
            <li><a href="{% url 'data:bank_wallets_home' %}">
              <img style="width: 20px;margin-{{'right'|invert_dir:LANGUAGE_CODE}}: 6px;margin-bottom: 9px;" src="{% static 'img/wallet_money.png' %}">{% trans 'Bank Wallets/Orange Cash' %}</a></li>
            <li><a href="{% url 'data:bank_cards_home' %}"><i class="fa fa-credit-card"></i>{% trans 'Bank Accounts/Cards' %}</a></li>
          {% endif %}

          {% if request.user.is_root or request.user.is_checker %}
            <li>
              <a href="{% url 'disbursement:single_step_list_create' %}?issuer=wallets&page=1">
                <i class="fa fa-flash"></i>{% trans 'Single Step Transactions' %}
              </a>
            </li>
            {% if not request.user.from_accept %}
              <li>
                <a href="{% url 'disbursement:create_payment_link' %}?page=1">
                  <i class="nav-icon fa fa-link"></i>{% trans 'Payment Links' %}
                </a>
              </li>
            {% endif %}
          {% endif %}
        {% endif %}

        {% if request.user.is_root %}
          {% if not request.user.from_accept %}
            <li><a><i class="fa fa-users"></i>{% trans 'Members' %} <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a>{% trans 'Add member' %}<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="{% url 'users:add_maker' %}">{% trans 'Maker' %}</a></li>
                  <li><a href="{% url 'users:add_checker' %}">{% trans 'Checker' %}</a></li>
                </ul>
              </li>
              <li><a href="{% url 'users:members' %}">{% trans 'All members' %}</a></li>
            </ul>
            </li>
            <li>
              <a href="{% url 'disbursement:balance_inquiry' username=request.user.username %}">
                <i class="fa fa-suitcase"></i>{% trans 'Balance Inquiry' %}
              </a>
            </li>
            {% if request.user.is_accept_vodafone_onboarding %}
              <li>
                <a href="{% url 'utilities:merchant_limit_edit' request.user.username %}">
                  <i class="fa fa-gear"></i>{% trans 'Merchant Limit'%}
                </a>
              </li>
            {% endif %}
          {% elif request.user.from_accept and request.user.allowed_to_be_bulk %}
            <li><a><i class="fa fa-users"></i>{% trans 'Members' %} <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a>{% trans 'Add member' %}<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="{% url 'users:add_maker' %}">{% trans 'Maker' %}</a></li>
                  <li><a href="{% url 'users:add_checker' %}">{% trans 'Checker' %}</a></li>
                </ul>
              </li>
              <li><a href="{% url 'users:members' %}">{% trans 'All members' %}</a></li>
            </ul>
            </li>
            <li><a href="{% url 'disbursement:balance_inquiry' username=request.user.username %}">
              <i class="fa fa-suitcase"></i>{% trans 'Balance Inquiry' %}
            </a>
            </li>
          {% endif %}



          {% if not request.user.is_vodafone_default_onboarding and not request.user.is_banks_standard_model_onboaring%}
            {% if not request.user.from_accept %}
              <li>
              <a>
            <img style="width: 19px;margin-right: 6px;" src="{% static 'img/money_plus.png' %}">{% trans 'Topup balance' %}
            <span class="fa fa-chevron-down"></span>
              </a>
              <ul class="nav child_menu">
              <li><a href="{% url 'utilities:transfer_request' %}">{% trans 'Add topup balance Request' %}</a></li>
              <li><a href="{% url 'utilities:list_transfer_request' %}">{% trans 'All topup balance requests' %}</a></li>
              </ul>
              </li>
            {% elif request.user.from_accept and request.user.allowed_to_be_bulk %}
            <li>
              <a>
            <img style="width: 19px;margin-right: 6px;" src="{% static 'img/money_plus.png' %}">{% trans 'Topup balance' %}
            <span class="fa fa-chevron-down"></span>
              </a>
              <ul class="nav child_menu">
              <li><a href="{% url 'utilities:transfer_request' %}">{% trans 'Add topup balance Request' %}</a></li>
              <li><a href="{% url 'utilities:list_transfer_request' %}">{% trans 'All topup balance requests' %}</a></li>
              </ul>
              </li>
            {% endif %}
          {% endif %}
        {% endif %}

        <li>
          <a href="{% url 'users:profile' request.user.username %}">
            <i class="fa fa-user"></i>{% trans 'Profile' %}
          </a>
        </li>
        <li>
          <a href="{% url 'users:session_list' %}">
            <i class="fa fa-clock-o"></i>{% trans 'Active Sessions' %}
          </a>
        </li>

        {% if request.user.is_root or request.user.is_maker %}
          {% if not request.user.from_accept %}
          <li><a><i class="fa fa-cog"></i>{% trans 'Settings' %}<span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              {% if request.user.is_root %}
                <li><a href="{% url 'users:levels' %}">{% trans 'levels' %}</a></li>
                <li><a href="{% url 'data:list_format' %}">{% trans 'Formats' %}</a></li>
                {% if request.user.is_accept_vodafone_onboarding %}
                <li><a href="{% url 'users:change_pin' %}">{% trans 'Change Pin' %}</a></li>
                {% endif %}
                {% if request.user.is_vodafone_default_onboarding %}
                <li><a href="{% url 'users:vodafone_change_pin' %}">{% trans 'Change Pin' %}</a></li>
                {% endif %}


              {% elif request.user.is_maker  %}
                <li><a href="{% url 'data:list_format' %}">{% trans 'Formats' %}</a></li>
              {% endif %}
            </ul>
          </li>
          {% elif request.user.from_accept and request.user.allowed_to_be_bulk %}
          <li><a><i class="fa fa-cog"></i>{% trans 'Settings' %}<span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              {% if request.user.is_root %}
                <li><a href="{% url 'users:levels' %}">{% trans 'levels' %}</a></li>
                <li><a href="{% url 'data:list_format' %}">{% trans 'Formats' %}</a></li>
                {% if request.user.is_accept_vodafone_onboarding %}
                <li><a href="{% url 'users:change_pin' %}">{% trans 'Change Pin' %}</a></li>
                {% endif %}
              {% elif request.user.is_maker  %}
                <li><a href="{% url 'data:list_format' %}">{% trans 'Formats' %}</a></li>
              {% endif %}
            </ul>
          </li>
          {% endif %}
        {% endif %}
      </ul>
    </div>
  </div>
  {# End of Sidebar menu #}

</div>

templates/flash_messages.html
<!--Handle flash messages-->
<div class="row">
  <div class="col-lg-12">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      <p>{{ message }}</p>
    </div>
    {% endfor %}
    {% endif %}
  </div>
  <!--End of Handle flash messages-->

templates/footer.html
{% load i18n %}
{% load custom_tags %}
{% get_current_language as LANGUAGE_CODE %}

<div class="pull-{{'right'|invert_dir:LANGUAGE_CODE}}">
    <a href="https://www.paymobsolutions.com">{% trans 'Paymob' %}</a> - {% trans 'Payouts Solution'%}
</div>
<div class="clearfix"></div>

templates/head_base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{LANGUAGE_CODE}}" dir="{% if LANGUAGE_CODE == 'en' %}ltr{%else%}rtl{%endif%}">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>{% block title %}{% endblock %} | Paymob</title>
    {% include 'base_css.html' %}
    {% block gentellacss %}{% endblock %}
    {% block customcss %}{% endblock %}
</head>

{%block body_content%}
{%endblock%}
</html>

templates/instant_api_sidebar.html
{% load static %}
{% load i18n %}
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="text-align:center; padding-top:12px;">
    {% if brand_logo %}
        <a href="{% url 'instant_cashin:transactions_list' %}" class="site_title">
            <span><img class="center" src="{{ brand_logo }}" height="38px" id="paymob_logo"></span>
        </a>
    {%else%}
        <a href="{% url 'instant_cashin:transactions_list' %}" class="site_title">
            <span><img class="center" src="{% static 'img/pm_name.png' %}" height="38px" id="paymob_logo"></span>
        </a>
    {%endif%}

  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">
    <div class="profile_pic">
      <img src="{{ request.user.avatar_thumbnail.url }}" alt="..." class="img-circle profile_img">
    </div>
    <div class="profile_info">
      <span>{% trans 'Welcome,' %}</span>
      <h2>
        {% if request.user.get_full_name %}
            {{ request.user.get_full_name }}
        {%else%}
            {{ request.user.username }}
        {%endif%}
      </h2>
    </div>
  </div>
  <!-- /menu profile quick info -->

  <br/>

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">

      <ul class="nav side-menu">
        {% if request.user.can_view_docs %}
            <li><a href="{% url 'docs:instant_docs' path='' %}"><i class="fa fa-book"></i> {% trans 'API Documentation'%}</a></li>
        {% endif %}

        <li><a><i class="fa fa-life-ring"></i> {% trans 'Settings' %} <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'users:profile' request.user.username %}">{% trans 'Profile' %}</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  <!-- /sidebar menu -->

</div>

templates/superadmin_sidebar.html
{% load static %}
{% load i18n %}

<div class="left_col scroll-view">

  {% include "sidebar_logo.html" %}

  {# sidebar menu #}
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <ul class="nav side-menu">

        <li><a><i class="fa fa-users"></i>{% trans 'Clients'%} <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'users:add_client' %}">{% trans 'New Client' %}</a></li>
            <li><a href="{% url 'users:clients' %}">{% trans 'All Clients' %}</a></li>
            {% if not request.user.is_banks_standard_model_onboaring %}
            <li><a href="{% url 'users:add_support' %}">{% trans 'New Support Member' %}</a></li>
            <li><a href="{% url 'users:support' %}">{% trans 'All Support Members' %}</a></li>
            <li><a href="{% url 'users:add_onboard_user' %}">{% trans 'New Onboard Member' %}</a></li>
            <li><a href="{% url 'users:onboard_user' %}">{% trans 'All Onboard Members' %}</a></li>
            <li><a href="{% url 'users:add_supervisor_user' %}">{% trans 'New Supervisor Member' %}</a></li>
            <li><a href="{% url 'users:supervisor' %}">{% trans 'All Supervisor Members' %}</a></li>
            {% endif %}
          </ul>
        </li>

        {% if request.user.is_accept_vodafone_onboarding or request.user.is_vodafone_facilitator_onboarding %}
          <li><a href="{% url 'disbursement:agents_list' %}"><i class="fa fa-th-list"></i>{% trans 'Agents'%}</a></li>
          <li><a href="{% url 'users:super_fees_profile' %}"><i class="fa fa-sliders"></i>{% trans 'Fees Profile'%}</a></li>
        {% elif request.user.is_instant_model_onboarding %}
          <li><a href="{% url 'disbursement:agents_list' %}"><i class="fa fa-th-list"></i>{% trans 'Agents'%}</a></li>
          <li><a href="{% url 'docs:instant_docs' path='' %}" rel="noopener" target="_blank"><i class="fa fa-book"></i>{% trans 'API Documentation'%}</a></li>
        {% endif %}

        <li><a href="{% url 'users:profile' request.user.username %}"><i class="fa fa-user"></i>{% trans 'Profile' %}</a></li>
        <li><a href="{% url 'users:session_list' %}"><i class="fa fa-clock-o" ></i>{% trans 'Active Sessions' %}</a></li>
        <li><a href="{% url 'users:entity_branding' %}"><i class="fa fa-adjust"></i>{% trans 'Branding' %}</a></li>
      </ul>
    </div>
  </div>
  {# End of Sidebar menu #}

</div>