data/urls.py
from django.urls import path

from data import views

app_name = 'data'

urlpatterns = [
    path('', views.redirect_home, name='main_view'),
    path('collection/', views.collection_home, name='collection_home'),
    path(
        'disbursement/e-wallets/',
        views.DisbursementHomeView.as_view(),
        name='e_wallets_home',
    ),
    path(
        'disbursement/bank-wallets/',
        views.BanksHomeView.as_view(),
        name='bank_wallets_home',
    ),
    path(
        'disbursement/bank-cards/',
        views.BanksHomeView.as_view(),
        name='bank_cards_home',
    ),
    path('delete/(<pk>/', views.FileDeleteView.as_view(), name='file_delete'),
    path('documents/<doc_id>/', views.document_view, name='doc_viewer'),
    path('download_doc/<doc_id>/', views.doc_download, name='download_doc'),
    path('format/list', views.FormatListView.as_view(), name='list_format'),
    path(
        'document/collection/<pk>/',
        views.RetrieveCollectionData.as_view(),
        name='doc_collection_detail',
    ),
    path(
        'transaction/report-problem/<trx_type>/<trx_id>/',
        views.ReportProblemView.as_view(),
        name='report_problem',
    ),
]

users/urls.py
# -*- coding: utf-8 -*-

from django.contrib.auth import views as django_auth_views
from django.urls import path
from oauth2_provider import views as oauth2_views

from payouts.views import no_agent_error_view
from users.views.main_views import CallbackURLEdit

from . import views

app_name = 'users'


client_urls = [
    path('clients/', views.Clients.as_view(), name='clients'),
    path('client/creation/', views.SuperAdminRootSetup.as_view(), name='add_client'),
    path(
        'client/delete/<str:username>/',
        views.SuperAdminCancelsRootSetupView.as_view(),
        name='delete_client',
    ),
    # 'Adding agents' -url- to the clients is at the disb. app urlpatterns
    path(
        'client/fees-setup/<token>/', views.ClientFeesSetup.as_view(), name='add_fees'
    ),
    path(
        'fees-profile/',
        views.SuperAdminFeesProfileTemplateView.as_view(),
        name='super_fees_profile',
    ),
    path(
        'client/fees-setup/edit/<str:username>/',
        views.CustomClientFeesProfilesUpdateView.as_view(),
        name='update_fees',
    ),
    path(
        'client/fees-setup/update/<str:username>/',
        views.ClientFeesUpdate.as_view(),
        name='update_fees_profile',
    ),
    path('client/toggle/', views.toggle_client, name='toggle'),
]

super_and_root_urls = [
    path('members/', views.Members.as_view(), name='members'),
    path('user/delete/', views.UserDeleteView.as_view(), name='delete'),
    path('settings/branding/', views.EntityBranding.as_view(), name='entity_branding'),
]

support_urls = [
    path('support/home/', views.SupportHomeView.as_view(), name='support_home'),
    path(
        'support/documents/<username>/',
        views.DocumentsForSupportListView.as_view(),
        name='documents_list',
    ),
    path(
        'support/documents/<username>/<doc_id>/',
        views.DocumentForSupportDetailView.as_view(),
        name='doc_detail',
    ),
    path('support/', views.SupportUsersListView.as_view(), name='support'),
    path(
        'support/creation/',
        views.SuperAdminSupportSetupCreateView.as_view(),
        name='add_support',
    ),
    path(
        'support/clients/',
        views.ClientsForSupportListView.as_view(),
        name='support_clients_list',
    ),
    path(
        'support/clients/Credentials',
        views.OnboardingNewInstantAdmin.as_view(),
        name='support_clients_credentials',
    ),
    path(
        'support/clients/Credentials/<client_id>',
        views.ClientCredentialsDetails.as_view(),
        name='support_clients_credentials_details',
    ),
]

onboard_user_urls = [
    path(
        'onboard-user/home/',
        views.OnbooardUserHomeView.as_view(),
        name='onboard_user_home',
    ),
    path('onboard-user/', views.OnboardUsersListView.as_view(), name='onboard_user'),
    path(
        'onboard-user/creation/',
        views.SuperAdminOnboardSetupCreateView.as_view(),
        name='add_onboard_user',
    ),
]

supervisor_user_urls = [
    path(
        'supervisor/home/',
        views.SupervisorUserHomeView.as_view(),
        name='supervisor_home',
    ),
    path('supervisor/', views.SupervisorUsersListView.as_view(), name='supervisor'),
    path(
        'supervisor/creation/',
        views.SuperAdminSupervisorSetupCreateView.as_view(),
        name='add_supervisor_user',
    ),
    path(
        'supervisor/reactivate_support_user',
        views.SupervisorReactivateSupportView.as_view(),
        name='reactivate_support_user',
    ),
]

disbursement_setups_urls = [
    path(
        'setting-up/disbursement-pin',
        views.PinFormView.as_view(),
        name='setting-disbursement-pin',
    ),
    path(
        'setting-up/disbursement-makers',
        views.MakerFormView.as_view(),
        name='setting-disbursement-makers',
    ),
    path(
        'setting-up/disbursement-levels',
        views.LevelsFormView.as_view(),
        name='setting-disbursement-levels',
    ),
    path(
        'setting-up/disbursement-checkers',
        views.CheckerFormView.as_view(),
        name='setting-disbursement-checkers',
    ),
    path(
        'setting-up/disbursement-formats',
        views.CategoryFormView.as_view(),
        name='setting-disbursement-formats',
    ),
    path('members/maker/add/', views.AddMakerView.as_view(), name='add_maker'),
    path('members/checker/add/', views.AddCheckerView.as_view(), name='add_checker'),
    path('levels/', views.LevelsView.as_view(), name='levels'),
    path('change_pin/', views.change_pin_view, name='change_pin'),
    path(
        'vodafone/change-pin/',
        views.vodafone_change_pin_view.as_view(),
        name='vodafone_change_pin',
    ),
]

instant_urls = [
    path('members/viewer/add/', views.ViewerCreateView.as_view(), name='add_viewer'),
    path(
        'members/api-checker/add/',
        views.APICheckerCreateView.as_view(),
        name='add_api_checker',
    ),
]

password_handling_urls = [
    path('change_password/<user>/', views.change_password, name="change_password"),
    path(
        'forgot-password/', views.ForgotPasswordView.as_view(), name="forgot_password"
    ),
    path('password/reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path(
        'password/reset/done/',
        django_auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'password/reset/<uidb64>/<token>/',
        django_auth_views.PasswordResetConfirmView.as_view(
            success_url='/', template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'password/done/',
        django_auth_views.PasswordResetCompleteView.as_view(),
        {'extra_context': {'login_url': '/user/login'}},
        name='password_reset_complete',
    ),
]

oauth2_provider_urls = [
    path("api/secure/o/token/", oauth2_views.TokenView.as_view(), name="oauth2_token"),
    path(
        "oauth2/keys/<username>/",
        views.OAuth2ApplicationDetailView.as_view(),
        name="oauth2_detail",
    ),
]

sessions_urls = [
    path('sessions/', views.SessionListView.as_view(), name='session_list'),
    path(
        'sessions/other/delete/',
        views.SessionDeleteOtherView.as_view(),
        name='session_delete_other',
    ),
    path(
        'sessions/<str:pk>/delete/',
        views.SessionDeleteView.as_view(),
        name='session_delete',
    ),
]

system_urls = [
    path(
        'creation/admin/<token>/',
        views.OnboardingNewMerchant.as_view(),
        name='creation_admin',
    ),
]

urlpatterns = [
    path('user/login/', views.login_view, name='user_login_view'),
    path('user/logout/', views.ourlogout, name='logout'),    
    path('user/no-agent/', no_agent_error_view, name='no_agent_error'),
    path('account/token/', views.OTPLoginView.as_view(), name='otp_login'),
    path('redirect/', views.RedirectPageView.as_view(), name='redirect'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path(
        'profile/edit/<username>/',
        views.ProfileUpdateView.as_view(),
        name='edit_profile',
    ),
    path('edit-level/<username>/', views.LevelUpdateView.as_view(), name='edit_level'),
    path(
        'callback/edit/<username>/',
        CallbackURLEdit.as_view(),
        name='api_viewer_callback',
    ),
]


urlpatterns += client_urls
urlpatterns += super_and_root_urls
urlpatterns += support_urls
urlpatterns += onboard_user_urls
urlpatterns += supervisor_user_urls
urlpatterns += disbursement_setups_urls
urlpatterns += instant_urls
urlpatterns += password_handling_urls
urlpatterns += oauth2_provider_urls
urlpatterns += sessions_urls
urlpatterns += system_urls

users/models/access_token.py
from uuid import uuid4

from django.db import models


class AccessToken(models.Model):
    token = models.CharField(max_length=255)
    used = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = uuid4()
        return super(AccessToken, self).save(*args, **kwargs)

users/models/admin.py
from .base_user import User, UserManager


class AdminManager(UserManager):
    """
    Manager for the SuperAdmin user
    """
    def get_queryset(self):
        return super(AdminManager, self).get_queryset().filter(user_type=0)

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('user_type', 0)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)


class SuperAdminUser(User):
    """
    SuperAdmin user who starts/manages the chain/process
    """
    objects = AdminManager()

    class Meta:
        proxy = True

    def first_non_super_agent(self, wallet_issuer=None):
        """
        Return the first non super agent to be used at the instant disbursement
        :param wallet_issuer: type of the passed wallet issuer
        :return: the first non super agent or None
        """
        msisdn_issuer_type = "E" if wallet_issuer.lower() == "etisalat" else "V"

        if self.agents:
            qs = self.agents.filter(super=False, type=msisdn_issuer_type)
            if qs.count() > 0:
                return qs.order_by("?").first().msisdn

        raise ValueError(f"{self.username} root/wallet_issuer has no agents setup.")

users/models/brand.py
from django.db import models

from imagekit.models import ProcessedImageField


class Brand(models.Model):
    """
    Entity Brand
    """
    color = models.CharField(max_length=20, null=True, blank=True)
    logo = ProcessedImageField(upload_to='entities_logo',
                               format='JPEG',
                               options={'quality': 60}, null=True, default='entities_logo/send_new_logo.png')

    mail_subject = models.CharField(max_length=200, null=True, blank=True, default='Paymob Send')

users/models/checker.py
from .base_user import User, UserManager


class CheckerManager(UserManager):
    """
    Manager for the Checker user
    """
    def get_queryset(self):
        return super(CheckerManager, self).get_queryset().filter(
            user_type=2)

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('user_type', 2)
        extra_fields.setdefault('is_superuser', False)
        if 'hierarchy' not in extra_fields:
            raise ValueError('The given hierarchy must be set')
        return self._create_user(username, email, password, **extra_fields)


class CheckerUser(User):
    """
    Checker user who reviews and disburses files uploaded by his same hierarchy levels of makers
    """
    objects = CheckerManager()

    class Meta:
        proxy = True

users/models/client.py
from django.core.validators import MaxValueValidator, MinLengthValidator
from django.db import models
from django.shortcuts import reverse
from django.utils.translation import gettext_lazy as _

from ..models import User


class ClientManager(models.Manager):
    """
    Manager for the Client model
    """

    def toggle(self, *args, **kwargs):
        """Toggle client object activation state"""
        try:
            user = self.get(*args, **kwargs)
            user.toggle_activation()
            return True
        except:
            return False


class Client(models.Model):
    """
    Model to track/manage entities/clients per SuperAdmin user
    """

    # Agents onboarding choices
    NEW_SUPERAGENT_AGENTS = 0
    EXISTING_SUPERAGENT_NEW_AGENTS = 1
    EXISTING_SUPERAGENT_AGENTS = 2
    P2M = 3
    AGENTS_ONBOARDING_CHOICES = [
        (NEW_SUPERAGENT_AGENTS, _("New superagent and new agents")),
        (EXISTING_SUPERAGENT_NEW_AGENTS, _("Existing superagent and new agents")),
        (EXISTING_SUPERAGENT_AGENTS, _("Existing superagent and existing agents")),
        (P2M, _("P2M Agent")),
    ]

    is_active = models.BooleanField(default=True)
    fees_percentage = models.PositiveSmallIntegerField(validators=[MaxValueValidator(100)], default=100)
    vodafone_facilitator_identifier = models.CharField(
            _("Vodafone facilitator unique identifier"),
            max_length=150,
            validators=[MinLengthValidator(10)],
            default='',
            null=True,
            blank=True
    )
    custom_profile = models.CharField(
            max_length=50,
            default='',
            null=True,
            blank=True,
            help_text=_("Custom profile name/constant ONLY for clients with custom budgets")
    )
    smsc_sender_name = models.CharField(
            max_length=11,
            default='',
            null=True,
            blank=True,
            help_text=_("SMSC sender name for naming the header of the sms sent at every vf bulk disbursement request")
    )
    agents_onboarding_choice = models.PositiveSmallIntegerField(
            _("Agents Onboarding Choice"),
            db_index=True,
            choices=AGENTS_ONBOARDING_CHOICES,
            default=NEW_SUPERAGENT_AGENTS
    )
    client = models.OneToOneField('users.RootUser', on_delete=models.CASCADE, related_name='client', null=True)
    creator = models.ForeignKey('users.SuperAdminUser', on_delete=models.SET_NULL, related_name='clients', null=True)
    onboarded_by = models.ForeignKey('users.OnboardUser', on_delete=models.SET_NULL, related_name='my_clients', null=True,blank=True)

    objects = ClientManager()

    class Meta:
        ordering = ['-id']

    def __str__(self):
        """:return: String representation of each client object"""
        return f'The client: {self.client.username} owned by superadmin: {self.creator}'

    def get_absolute_url(self):
        """Success form submit - object saving url"""
        return reverse("users:update_fees", kwargs={'username': self.client.username})

    def toggle_activation(self):
        """Toggle user activation status from active to non-active and vice versa"""
        self.is_active = not self.is_active
        self.save()
        self.client.is_active = self.is_active
        self.client.save()

    def delete_client(self):
        """Delete all users (makers & checkers) created by specific client whenever deleting it"""
        User.objects.filter(hierarchy=self.client.hierarchy).delete()
        self.delete()

    def get_fees(self):
        """
        Used at the change profile request
        :return: String/Constant that will be used as a value of the NEWPROFILE key
        """
        if self.custom_profile:
            return self.custom_profile
        elif self.fees_percentage == 100:
            return "Full"
        elif self.fees_percentage == 50:
            return "Half"
        else:
            return "No fees"

users/models/instant_api_checker.py
from .base_user import User, UserManager


class InstantAPICheckerManager(UserManager):
    """
    Manager for the Instant API Checker user
    """
    def get_queryset(self):
        return super().get_queryset().filter(user_type=6)

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('user_type', 6)
        extra_fields.setdefault('is_superuser', False)
        if 'hierarchy' not in extra_fields:
            raise ValueError('The given hierarchy must be set')
        return self._create_user(username, email, password, **extra_fields)


class InstantAPICheckerUser(User):
    """
    Instant API Checker user who can disburse instantly through and API endpoint
    """
    objects = InstantAPICheckerManager()

    class Meta:
        proxy = True

users/models/instant_api_viewer.py
from .base_user import User, UserManager


class InstantAPIViewerManager(UserManager):
    """
    Manager for the Instant API Viewer user
    """
    def get_queryset(self):
        return super().get_queryset().filter(user_type=7)

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('user_type', 7)
        extra_fields.setdefault('is_superuser', False)
        if 'hierarchy' not in extra_fields:
            raise ValueError('The given hierarchy must be set')
        return self._create_user(username, email, password, **extra_fields)


class InstantAPIViewerUser(User):
    """
    Instant API Viewer user has the ability to search/view all transactions done via his corresponding APIChecker
    """
    objects = InstantAPIViewerManager()

    class Meta:
        proxy = True

templates/users/entity_branding.html
{% extends 'new_base.html' %}
{% load i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}
{% load custom_tags %}

{% block title %} {% trans 'Branding' %} {% endblock %}

{% block gentellacss %}
<link href="{% static 'gentella/vendors/mjolnic-bootstrap-colorpicker/bootstrap-colorpicker.min.css' %}" rel="stylesheet">

{%endblock%}

{% block body %}


<div class="page-title">
    <div class="title_left">
        <h3>{% trans 'Entity Branding' %}</h3>
    </div>


    <div class="clearfix">

    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="{% url 'users:entity_branding' %}" method="post" class="form-horizontal" enctype="multipart/form-data">

                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">{% trans 'Color' %}</label>
                            <div class="col-md-4 col-sm-4 col-xs-7">
                                
                                <div id="color-picker" class="input-group colorpicker-component">
                                    <input type="text" class="form-control" />
                                    <span class="input-group-addon"><em></em></span>
                                </div>
                                    
                                
                            </div>
                        </div>
                        
                        {% for field in form.visible_fields %}
                            {% if forloop.first %}
                            {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                            {% endfor %}
                            {% endif %}
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">{{ field.label|capfirst }}</label>
                                <div class="col-md-6 col-sm-9 col-xs-12">
                                    {{ field.errors.as_ul }}
                                    {{ field }}
                                </div>
                            </div>


                        {% endfor %}
                        <input type="submit" value="{% trans 'submit' %}" class="btn btn-upload btn-success pull-{{'right'|invert_dir:LANGUAGE_CODE}}">
                    </form>


                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->

</div>
{% endblock %}

{% block script %}
<script src="{% static 'gentella/vendors/mjolnic-bootstrap-colorpicker/bootstrap-colorpicker.min.js' %}"></script>

<script>
    $(document).ready(function () {
        let default_color = '#ffaa00'
        if ( '{{brand_color}}' != 'None'){
            default_color = '{{brand_color}}'
        }
        
        $('#color-picker').colorpicker({
            color: default_color,
            format:'hex'
        }).on('changeColor', function (e) {
            
            let color = e.color.toString('rgba');
            let color_hex = e.color.toString('hex');
            $('input[name=color]').val(color_hex);
            $('.left_col .scroll-view').css('background-color', color);
            $('html').css('background-color', color);
            $('.site_title').css('background-color', color);
            $('.nav_title').css('background', color);
            $('.container').css('background', color);
            $('.main_container').css('background', color);
            
            
            let frm = ColorLuminance(color_hex, -0.02);
            let to = ColorLuminance(frm, -0.05);
            let color_gradient = '-webkit-gradient(linear, left top, left bottom, from(' + to + '), to(' + frm + '))'
            let $SIDEBAR_MENU = $('#sidebar-menu');
            let atag = $SIDEBAR_MENU.find('a');
            if ($(atag).parent().is('.active')) {

                $(atag).css('background', color_gradient);
            }
            $SIDEBAR_MENU.find('.current-page').find('a').removeAttr('style');
            $SIDEBAR_MENU.find('a').on('click', function (ev) {
                let $li = $(this).parent();
                
                if ($li.is('.active')) {
                    $(this).css('background', color_gradient);
                }
            });
            $('body').css('color', ColorLuminance(color_hex, -0.5));
            $(".nav.child_menu li a").on('mouseover', function (ev) {
                $(this).removeAttr('style');
            });
            
            $('.fa-bars').css('color', color_hex);
            $('#sidebar-div').css('background', color_hex);
            //small menu
            $("#menu_toggle").on('click', function (e) {
                $('.nav-sm ul.nav.child_menu').css('background', color_hex)
            });
            $('head').append('<style>.nav-md ul.nav.child_menu li:before{background:'+ to+' !important;}</style>');
            
        });
        
        
       
    });    
</script>

{% endblock %}

templates/users/password_reset_confirm.html
{% extends 'base_form_singlepage.html' %}
{% load i18n %}
{% block title %} {% trans 'Create Password' %} {% endblock %}

{% block form %}
{% if validlink %}
<form method="POST" action=".">
    {% csrf_token %}
    <h1>{% trans 'Create Password' %}</h1>
    
    {{ form.non_field_errors }}

    <div>
        <input type="password" class="form-control" name="new_password1" placeholder='{% trans "New Passowrd" %}' required>
        {{ form.new_password1.errors }}
    </div>
    <div>
        <input type="password" class="form-control" name="new_password2" placeholder='{% trans "New Passowrd Confirmation" %}' required>
        {{ form.new_password2.errors }}
    </div>

    <div><button class="submit btn btn-lg btn-default btn-block" type="submit">
            {% trans 'Submit' %}</button></div>
    <div class="clearfix"></div>

    <div class="separator">

        <div class="clearfix"></div>
        <br />

        <div>
            <h1>{% trans 'Payouts Dashboard' %}</h1>
            <p>©{% now "Y" %}{% trans ' All Rights Reserved. Payouts Dashoard! is a Paymob solution. Privacy and Terms' %}</p>
        </div>
    </div>
</form>
{%else%}

<h1>{% trans 'This url is not Valid or used before.' %}</h1>
<br>
<a href="{% url 'data:main_view' %}">{% trans 'Home' %}</a>
<div class="separator">

    <div class="clearfix"></div>
    <br />

    <div>
          <h1>{% trans 'Payouts Dashboard' %}</h1>
          <p>©{% now "Y" %}{% trans ' All Rights Reserved. Payouts Dashoard! is a Paymob solution. Privacy and Terms' %}</p>
    </div>
</div>
{%endif%}

{% endblock %}

templates/users/profile.html
{% extends 'new_base.html' %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load custom_tags %}

{% block title %}{{ request.user.username }} {% trans 'profile' %}{% endblock %}
{% block body %}
    <div class="page-title">
      <div class="title_left">
          <h3>{{ object.get_full_name }}</h3>
      </div>

      <div class="clearfix"></div>

      <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                  <div class="row">
                    <div class="col-md-3 col-lg-3 ">
                      <img alt="User Pic" src="{{ object.avatar_thumbnail.url }}" class="img-circle img-responsive">
                    </div>
                    <div class=" col-md-9 col-lg-9 ">
                      <table class="table table-user-information">
                        <tbody>
                          <tr>
                            <td>{% trans 'Title:' %}</td>
                            <td>{{ object.title }}</td>
                          </tr>
                          <tr>
                            <td>{% trans 'First Name:' %}</td>
                            <td>{{ object.first_name }}</td>
                          </tr>
                          <tr>
                            <td>{% trans 'Last Name:' %}</td>
                            <td>{{ object.last_name }}</td>
                          </tr>
                          <tr>
                            <td>{% trans 'Join date:' %}</td>
                            <td>{{ object.date_joined }}</td>
                          </tr>
                          <tr>
                            <td>{% trans 'Account Type:' %}</td>
                            <td>
                              {% if object.user_type == 0 %}
                                {% trans 'Super' %}
                              {% elif object.user_type == 1  %}
                                {% trans 'Maker' %}
                              {% elif object.user_type == 2 %}
                                {% trans 'Checker' %}
                              {% elif object.user_type == 3 %}
                                {% trans 'Admin' %}
                              {% elif object.user_type == 6 %}
                                {% trans 'API Checker' %}
                              {% elif object.user_type == 7 %}
                                {% trans 'API Viewer' %}
                              {% elif object.user_type == 8 %}
                                {% trans 'Support' %}
                              {% endif %}
                            </td>
                          </tr>
                          <tr>
                            <td>{% trans 'Email' %}</td>
                            <td><a href="mailto:{{ object.email }}">{{ object.email }}</a></td>
                          </tr>
                          <tr>
                            <td>{% trans 'Phone Number' %}</td>
                            <td>{{ object.mobile_no }}</td>
                          </tr>
                          <tr>
                            <td>{% trans 'IS Notified User' %}</td>
                            <td>
                              {% if object.is_notified_user %}
                                <span style="color: darkgreen;font-size: 25px;">&#10004;</span>
                              {% else %}
                                <span style="color: darkred;font-size: 25px;">&#10006;</span>
                              {% endif %}
                            </td>
                          </tr>
                        </tbody>
                      </table>

                    </div>
                  </div>
                </div>

                <div class="panel-footer">
                  <a data-original-title="Broadcast Message" data-toggle="tooltip" type="button"
                     class="btn btn-sm btn-primary disabled" href="#">
                    <em class="glyphicon glyphicon-envelope"></em>
                  </a>
                  <span class="pull-{{'right'|invert_dir:LANGUAGE_CODE}}">
                    <a href="{% url 'users:edit_profile' object.username %}" data-original-title="{% trans 'Edit Data' %}"
                       data-toggle="tooltip" type="button" class="btn btn-sm btn-warning">
                      <em class="glyphicon glyphicon-edit"></em></a>
                    {% ifequal request.user.username object.username %}
                    <a href="{% url 'users:change_password' request.user.username %}" data-original-title="{% trans 'Change Password' %}"
                       data-toggle="tooltip" type="button" class="btn btn-sm btn-danger">
                      <i class="fa fa-key"></i></a>
                    {% endifequal %}
                  </span>
                </div>
            </div>
          </div>
      </div>
    </div>
{% endblock %}

templates/users/redirect_page.html
{% extends 'base_form_singlepage.html' %}
{% load i18n %}
{% block title %} {% trans 'Choose Portal' %} {% endblock %}
{% block form %}
    <div class="pull-left">

        <a href="{% url 'users:redirect' %}?status=collection" class="btn btn-success btn-lg">{% trans 'Collection' %}</a>

    </div>

    <div class="pull-right">
    
        <a href="{% url 'users:redirect' %}?status=disbursement" class="btn btn-success btn-lg">{% trans 'Disbursement' %}</a>
    
    </div>
{% endblock %}